name: flame_dino
description: Dino runner game written using Flame.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  flame: ^1.12.0
  flame_audio: ^2.1.5
  flame_bloc: ^1.10.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: ArcadeClassic
      fonts:
        - asset: assets/fonts/arcade_classic.ttf
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/Pixelify_Sans.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/dino_launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

